package com.superadmin.controller;

import com.superadmin.model.*;
import com.superadmin.repository.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import org.springframework.security.access.prepost.PreAuthorize;
import java.util.*;

@RestController
@RequestMapping("/api/admin")
@CrossOrigin(origins = "*")
public class AdminController {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private InstitutionRepository institutionRepository;

    @Autowired
    private VehicleRepository vehicleRepository;

    @Autowired
    private DriverRepository driverRepository;

    @Autowired
    private RouteRepository routeRepository;

    @Autowired
    private StopRepository stopRepository;

    @Autowired
    private SubscriptionRepository subscriptionRepository;

    @Autowired
    private PaymentRepository paymentRepository;

    @Autowired
    private OfferRepository offerRepository;

    @Autowired
    private ComplaintRepository complaintRepository;

    // ==========================================
    // USER MANAGEMENT
    // ==========================================

    @GetMapping("/users")
    public List<User> getAllUsers() {
        return userRepository.findAll();
    }

    @GetMapping("/users/{id}")
    public ResponseEntity<User> getUserById(@PathVariable Long id) {
        return userRepository.findById(id)
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }

    @PutMapping("/users/{id}/status")
    public ResponseEntity<?> updateUserStatus(@PathVariable Long id, @RequestParam String status) {
        return userRepository.findById(id)
                .map(user -> {
                    user.setStatus(status.toUpperCase());
                    userRepository.save(user);
                    return ResponseEntity.ok(user);
                })
                .orElse(ResponseEntity.notFound().build());
    }

    @PutMapping("/users/{id}")
    public ResponseEntity<?> editUser(@PathVariable Long id, @RequestBody User userDetails) {
        return userRepository.findById(id)
                .map(user -> {
                    user.setEmail(userDetails.getEmail());
                    user.setUsername(userDetails.getUsername());
                    user.setRole(userDetails.getRole());
                    userRepository.save(user);
                    return ResponseEntity.ok(user);
                })
                .orElse(ResponseEntity.notFound().build());
    }

    @PostMapping("/users/{id}/generate-otp")
    public ResponseEntity<?> generateUserOtp(@PathVariable Long id) {
        return userRepository.findById(id)
                .map(user -> {
                    String otp = String.format("%06d", new java.util.Random().nextInt(999999));
                    user.setOtpCode(otp);
                    user.setOtpExpiry(java.time.LocalDateTime.now().plusMinutes(15));
                    userRepository.save(user);

                    Map<String, Object> resp = new HashMap<>();
                    resp.put("userId", user.getId());
                    resp.put("username", user.getUsername());
                    resp.put("email", user.getEmail());
                    resp.put("role", user.getRole());
                    resp.put("generatedOtp", otp);
                    resp.put("expiresAt", user.getOtpExpiry().toString());
                    resp.put("message", "Secure OTP generated by Super Admin and dispatched to user.");
                    return ResponseEntity.ok(resp);
                })
                .orElse(ResponseEntity.notFound().build());
    }

    // ==========================================
    // DRIVER MANAGEMENT
    // ==========================================

    @GetMapping("/drivers")
    public List<Driver> getAllDrivers() {
        return driverRepository.findAll();
    }

    @GetMapping("/drivers/{id}")
    public ResponseEntity<Driver> getDriverById(@PathVariable Long id) {
        return driverRepository.findById(id)
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }

    @PutMapping("/drivers/{id}")
    public ResponseEntity<?> editDriver(@PathVariable Long id, @RequestBody Driver driverDetails) {
        return driverRepository.findById(id)
                .map(driver -> {
                    driver.setName(driverDetails.getName());
                    driver.setEmail(driverDetails.getEmail());
                    driver.setPhone(driverDetails.getPhone());
                    driver.setAssignedVehicleId(driverDetails.getAssignedVehicleId());
                    driver.setRating(driverDetails.getRating());
                    driver.setStatus(driverDetails.getStatus());
                    driverRepository.save(driver);
                    return ResponseEntity.ok(driver);
                })
                .orElse(ResponseEntity.notFound().build());
    }

    // ==========================================
    // VEHICLE MANAGEMENT
    // ==========================================

    @GetMapping("/vehicles")
    public List<Vehicle> getAllVehicles() {
        return vehicleRepository.findAll();
    }

    @PostMapping("/vehicles")
    public Vehicle createVehicle(@RequestBody Vehicle vehicle) {
        if (vehicle.getVerificationStatus() == null) {
            vehicle.setVerificationStatus("PENDING");
        }
        return vehicleRepository.save(vehicle);
    }

    @PutMapping("/vehicles/{id}/status")
    public ResponseEntity<?> verifyVehicle(@PathVariable Long id, @RequestParam String status) {
        return vehicleRepository.findById(id)
                .map(vehicle -> {
                    vehicle.setVerificationStatus(status.toUpperCase());
                    vehicleRepository.save(vehicle);
                    return ResponseEntity.ok(vehicle);
                })
                .orElse(ResponseEntity.notFound().build());
    }

    @DeleteMapping("/vehicles/{id}")
    public ResponseEntity<?> deleteVehicle(@PathVariable Long id) {
        return vehicleRepository.findById(id)
                .map(vehicle -> {
                    vehicleRepository.delete(vehicle);
                    return ResponseEntity.ok().build();
                })
                .orElse(ResponseEntity.notFound().build());
    }

    // ==========================================
    // INSTITUTION MANAGEMENT
    // ==========================================

    @GetMapping("/institutions")
    public List<Institution> getAllInstitutions() {
        return institutionRepository.findAll();
    }

    @PostMapping("/institutions")
    public Institution createInstitution(@RequestBody Institution institution) {
        return institutionRepository.save(institution);
    }

    @PutMapping("/institutions/{id}")
    public ResponseEntity<?> updateInstitution(@PathVariable Long id, @RequestBody Institution details) {
        return institutionRepository.findById(id)
                .map(institution -> {
                    institution.setName(details.getName());
                    institution.setLocation(details.getLocation());
                    institution.setContact(details.getContact());
                    institution.setType(details.getType());
                    institution.setTransportRequirements(details.getTransportRequirements());
                    institutionRepository.save(institution);
                    return ResponseEntity.ok(institution);
                })
                .orElse(ResponseEntity.notFound().build());
    }

    @DeleteMapping("/institutions/{id}")
    public ResponseEntity<?> deleteInstitution(@PathVariable Long id) {
        return institutionRepository.findById(id)
                .map(institution -> {
                    institutionRepository.delete(institution);
                    return ResponseEntity.ok().build();
                })
                .orElse(ResponseEntity.notFound().build());
    }

    // ==========================================
    // ROUTE MANAGEMENT
    // ==========================================

    @GetMapping("/routes")
    public List<Route> getAllRoutes() {
        return routeRepository.findAll();
    }

    @PostMapping("/routes")
    public Route createRoute(@RequestBody Route route) {
        if (route.getStatus() == null) {
            route.setStatus("ACTIVE");
        }
        return routeRepository.save(route);
    }

    @PutMapping("/routes/{id}")
    public ResponseEntity<?> updateRoute(@PathVariable Long id, @RequestBody Route details) {
        return routeRepository.findById(id)
                .map(route -> {
                    route.setStartPoint(details.getStartPoint());
                    route.setEndPoint(details.getEndPoint());
                    route.setDemandLevel(details.getDemandLevel());
                    route.setTotalSeats(details.getTotalSeats());
                    route.setAvailableSeats(details.getAvailableSeats());
                    route.setPriceMonthly(details.getPriceMonthly());
                    route.setAssignedDriverId(details.getAssignedDriverId());
                    route.setAssignedVehicleId(details.getAssignedVehicleId());
                    route.setStatus(details.getStatus());
                    routeRepository.save(route);
                    return ResponseEntity.ok(route);
                })
                .orElse(ResponseEntity.notFound().build());
    }

    @DeleteMapping("/routes/{id}")
    public ResponseEntity<?> deleteRoute(@PathVariable Long id) {
        return routeRepository.findById(id)
                .map(route -> {
                    routeRepository.delete(route);
                    return ResponseEntity.ok().build();
                })
                .orElse(ResponseEntity.notFound().build());
    }

    // Route stops
    @GetMapping("/routes/{id}/stops")
    public List<Stop> getRouteStops(@PathVariable Long id) {
        return stopRepository.findByRouteIdOrderBySequenceAsc(id);
    }

    @PostMapping("/routes/{id}/stops")
    public Stop addRouteStop(@PathVariable Long id, @RequestBody Stop stop) {
        stop.setRouteId(id);
        return stopRepository.save(stop);
    }

    // ==========================================
    // SUBSCRIPTION MANAGEMENT
    // ==========================================

    @GetMapping("/subscriptions")
    public List<Subscription> getAllSubscriptions() {
        return subscriptionRepository.findAll();
    }

    // ==========================================
    // PAYMENT & COMMISSION
    // ==========================================

    @GetMapping("/payments")
    public List<Payment> getAllPayments() {
        return paymentRepository.findAll();
    }

    // ==========================================
    // OFFERS & PROMOTIONS
    // ==========================================

    @GetMapping("/offers")
    public List<Offer> getAllOffers() {
        return offerRepository.findAll();
    }

    @PostMapping("/offers")
    public Offer createOffer(@RequestBody Offer offer) {
        return offerRepository.save(offer);
    }

    @PutMapping("/offers/{id}")
    public ResponseEntity<?> updateOffer(@PathVariable Long id, @RequestBody Offer details) {
        return offerRepository.findById(id)
                .map(offer -> {
                    offer.setCode(details.getCode());
                    offer.setTitle(details.getTitle());
                    offer.setDiscountText(details.getDiscountText());
                    offer.setActive(details.getActive());
                    offerRepository.save(offer);
                    return ResponseEntity.ok(offer);
                })
                .orElse(ResponseEntity.notFound().build());
    }

    @DeleteMapping("/offers/{id}")
    public ResponseEntity<?> deleteOffer(@PathVariable Long id) {
        return offerRepository.findById(id)
                .map(offer -> {
                    offerRepository.delete(offer);
                    return ResponseEntity.ok().build();
                })
                .orElse(ResponseEntity.notFound().build());
    }

    // ==========================================
    // SAFETY & COMPLAINTS
    // ==========================================

    @GetMapping("/complaints")
    public List<Complaint> getAllComplaints() {
        return complaintRepository.findAll();
    }

    @PutMapping("/complaints/{id}/status")
    public ResponseEntity<?> updateComplaintStatus(@PathVariable Long id, @RequestParam String status) {
        return complaintRepository.findById(id)
                .map(complaint -> {
                    complaint.setStatus(status.toUpperCase());
                    complaintRepository.save(complaint);
                    return ResponseEntity.ok(complaint);
                })
                .orElse(ResponseEntity.notFound().build());
    }

    // ==========================================
    // ANALYTICS & AI INTEL
    // ==========================================

    @GetMapping("/analytics")
    public ResponseEntity<?> getAnalytics() {
        Map<String, Object> analytics = new HashMap<>();
        
        // Dynamic demand routes analytics
        List<Map<String, Object>> popularRoutes = new ArrayList<>();
        routeRepository.findAll().forEach(r -> {
            Map<String, Object> rMap = new HashMap<>();
            rMap.put("route", r.getStartPoint() + " ➔ " + r.getEndPoint());
            rMap.put("demand", r.getDemandLevel());
            rMap.put("utilization", Math.round(((double)(r.getTotalSeats() - r.getAvailableSeats()) / r.getTotalSeats()) * 100) + "%");
            popularRoutes.add(rMap);
        });
        
        // Sorting by utilization
        analytics.put("popularRoutes", popularRoutes);
        
        // Seat details
        int totalSeats = routeRepository.findAll().stream().mapToInt(Route::getTotalSeats).sum();
        int availableSeats = routeRepository.findAll().stream().mapToInt(Route::getAvailableSeats).sum();
        analytics.put("emptySeats", availableSeats);
        analytics.put("totalSeats", totalSeats);
        analytics.put("vehicleUtilization", totalSeats > 0 ? ((totalSeats - availableSeats) * 100) / totalSeats : 0);

        return ResponseEntity.ok(analytics);
    }

    @GetMapping("/ai/demand")
    public ResponseEntity<?> getAIDemandIntelligence() {
        List<Map<String, Object>> recommendations = new ArrayList<>();

        Map<String, Object> rec1 = new HashMap<>();
        rec1.put("corridor", "Kattur ➔ Chennai IT Park");
        rec1.put("demand", "High 🔥");
        rec1.put("studentsCount", 28);
        rec1.put("employeesCount", 46);
        rec1.put("availableSeats", 17);
        rec1.put("recommendation", "Add 3 vehicles to this corridor.");

        Map<String, Object> rec2 = new HashMap<>();
        rec2.put("corridor", "Tambaram ➔ ABC Matriculation School");
        rec2.put("demand", "Medium 📈");
        rec2.put("studentsCount", 19);
        rec2.put("employeesCount", 5);
        rec2.put("availableSeats", 4);
        rec2.put("recommendation", "Optimize route timing to save 8 minutes.");

        recommendations.add(rec1);
        recommendations.add(rec2);

        return ResponseEntity.ok(recommendations);
    }

    @GetMapping("/routes/search")
    public ResponseEntity<List<Map<String, Object>>> searchRoutes(
            @RequestParam(required = false) String origin,
            @RequestParam(required = false) String destination,
            @RequestParam(required = false) String institution,
            @RequestParam(required = false) String date,
            @RequestParam(required = false) String time) {
        
        List<Route> routes = routeRepository.findAll();
        List<Map<String, Object>> results = new ArrayList<>();
        
        for (Route route : routes) {
            if (origin != null && !origin.isEmpty() && !route.getStartPoint().toLowerCase().contains(origin.toLowerCase())) {
                continue;
            }
            if (destination != null && !destination.isEmpty() && !route.getEndPoint().toLowerCase().contains(destination.toLowerCase())) {
                continue;
            }
            if (institution != null && !institution.isEmpty() && !route.getEndPoint().toLowerCase().contains(institution.toLowerCase())) {
                continue;
            }
            if (!"ACTIVE".equalsIgnoreCase(route.getStatus())) {
                continue;
            }
            
            Map<String, Object> map = new HashMap<>();
            map.put("route", route);
            
            if (route.getAssignedVehicleId() != null) {
                vehicleRepository.findById(route.getAssignedVehicleId()).ifPresent(v -> {
                    map.put("vehicle", v);
                });
            }
            
            if (route.getAssignedDriverId() != null) {
                driverRepository.findById(route.getAssignedDriverId()).ifPresent(d -> {
                    map.put("driver", d);
                });
            }
            
            List<Stop> stops = stopRepository.findByRouteIdOrderBySequenceAsc(route.getId());
            map.put("stops", stops);
            
            results.add(map);
        }
        
        return ResponseEntity.ok(results);
    }

    // ==========================================
    // DEMAND ANALYTICS MODULE INTEGRATION
    // ==========================================
    @GetMapping("/analytics/demand-overview")
    public ResponseEntity<?> getDemandOverview(@RequestParam(required = false, defaultValue = "Apr 15, 2025") String date) {
        Map<String, Object> data = new HashMap<>();

        // 1. KPI Cards Summary
        data.put("date", date);
        data.put("totalDemand", 1248);
        data.put("totalDemandTrend", "+12% vs last week");
        data.put("availableSeats", 892);
        data.put("availableSeatsTrend", "-8% vs last week");
        data.put("activeRoutes", 86);
        data.put("activeRoutesTrend", "+6% vs last week");
        data.put("avgFillRate", 71);
        data.put("avgFillRateTrend", "+14% vs last week");

        // 2. Demand by Category
        Map<String, Object> categories = new HashMap<>();
        Map<String, Object> school = new HashMap<>();
        school.put("percentage", 32);
        school.put("count", 399);
        school.put("color", "#3b82f6");

        Map<String, Object> college = new HashMap<>();
        college.put("percentage", 28);
        college.put("count", 349);
        college.put("color", "#6366f1");

        Map<String, Object> work = new HashMap<>();
        work.put("percentage", 40);
        work.put("count", 500);
        work.put("color", "#10b981");

        categories.put("School", school);
        categories.put("College", college);
        categories.put("Work", work);
        data.put("demandByCategory", categories);

        // 3. Top Demand Routes
        List<Map<String, Object>> topRoutes = new ArrayList<>();
        
        Map<String, Object> r1 = new HashMap<>();
        r1.put("id", 1);
        r1.put("origin", "Kattur");
        r1.put("destination", "ABC College");
        r1.put("category", "College");
        r1.put("categoryColor", "bg-indigo-500/20 text-indigo-300 border-indigo-500/30");
        r1.put("demandCount", 68);
        r1.put("availableSeats", 12);
        r1.put("fillRate", 85);
        topRoutes.add(r1);

        Map<String, Object> r2 = new HashMap<>();
        r2.put("id", 2);
        r2.put("origin", "Kattur");
        r2.put("destination", "IT Park");
        r2.put("category", "Work");
        r2.put("categoryColor", "bg-emerald-500/20 text-emerald-300 border-emerald-500/30");
        r2.put("demandCount", 54);
        r2.put("availableSeats", 10);
        r2.put("fillRate", 84);
        topRoutes.add(r2);

        Map<String, Object> r3 = new HashMap<>();
        r3.put("id", 3);
        r3.put("origin", "Ariyankuppam");
        r3.put("destination", "School");
        r3.put("category", "School");
        r3.put("categoryColor", "bg-blue-500/20 text-blue-300 border-blue-500/30");
        r3.put("demandCount", 48);
        r3.put("availableSeats", 8);
        r3.put("fillRate", 86);
        topRoutes.add(r3);

        Map<String, Object> r4 = new HashMap<>();
        r4.put("id", 4);
        r4.put("origin", "Lawspet");
        r4.put("destination", "College");
        r4.put("category", "College");
        r4.put("categoryColor", "bg-indigo-500/20 text-indigo-300 border-indigo-500/30");
        r4.put("demandCount", 41);
        r4.put("availableSeats", 15);
        r4.put("fillRate", 73);
        topRoutes.add(r4);

        Map<String, Object> r5 = new HashMap<>();
        r5.put("id", 5);
        r5.put("origin", "Villupuram");
        r5.put("destination", "IT Park");
        r5.put("category", "Work");
        r5.put("categoryColor", "bg-emerald-500/20 text-emerald-300 border-emerald-500/30");
        r5.put("demandCount", 37);
        r5.put("availableSeats", 9);
        r5.put("fillRate", 80);
        topRoutes.add(r5);

        data.put("topDemandRoutes", topRoutes);

        // 4. Heat Map Hotspots
        List<Map<String, Object>> heatSpots = new ArrayList<>();
        Map<String, Object> h1 = new HashMap<>();
        h1.put("name", "Kattur");
        h1.put("demand", 68);
        h1.put("intensity", "Very High");
        h1.put("lat", 11.9360);
        h1.put("lng", 79.8320);
        heatSpots.add(h1);

        Map<String, Object> h2 = new HashMap<>();
        h2.put("name", "ABC College");
        h2.put("demand", 45);
        h2.put("intensity", "High");
        h2.put("lat", 11.9480);
        h2.put("lng", 79.8150);
        heatSpots.add(h2);

        Map<String, Object> h3 = new HashMap<>();
        h3.put("name", "IT Park");
        h3.put("demand", 54);
        h3.put("intensity", "Medium");
        h3.put("lat", 12.8390);
        h3.put("lng", 80.2180);
        heatSpots.add(h3);

        data.put("heatSpots", heatSpots);

        return ResponseEntity.ok(data);
    }

    // ==========================================
    // DRIVER KYC VERIFICATION AUDIT QUEUE
    // ==========================================
    @GetMapping("/drivers/kyc-queue")
    public ResponseEntity<?> getDriverKycQueue() {
        List<Map<String, Object>> kycQueue = new ArrayList<>();

        Map<String, Object> k1 = new HashMap<>();
        k1.put("id", 1L);
        k1.put("driverName", "Kumar Swamy");
        k1.put("phone", "+91 98401 23456");
        k1.put("email", "kumar.swamy@drivercabs.com");
        k1.put("vehiclePlate", "TN 01 AB 1234");
        k1.put("licenseNumber", "DL-TN-01-2021-9876");
        k1.put("licenseExpiry", "2031-08-15");
        k1.put("rcNumber", "RC-TN01AB1234");
        k1.put("insurancePolicy", "POL-HDFC-998231");
        k1.put("backgroundCheckStatus", "POLICE_VERIFIED");
        k1.put("backgroundCheckDoc", "CERT-BG-CH-4491.pdf");
        k1.put("status", "VERIFIED");
        k1.put("submittedAt", "2026-09-10T08:30:00");
        k1.put("auditedBy", "SuperAdmin Compliance Desk");
        k1.put("remarks", "All biometric and RTO records verified.");
        kycQueue.add(k1);

        Map<String, Object> k2 = new HashMap<>();
        k2.put("id", 2L);
        k2.put("driverName", "Ravi Chandran");
        k2.put("phone", "+91 98401 23457");
        k2.put("email", "ravi.chandran@cabs.com");
        k2.put("vehiclePlate", "TN 02 CD 5678");
        k2.put("licenseNumber", "DL-TN-02-2019-4451");
        k2.put("licenseExpiry", "2029-04-20");
        k2.put("rcNumber", "RC-TN02CD5678");
        k2.put("insurancePolicy", "POL-ICICI-881204");
        k2.put("backgroundCheckStatus", "PENDING_AUDIT");
        k2.put("backgroundCheckDoc", "CERT-BG-CH-7721.pdf");
        k2.put("status", "PENDING_AUDIT");
        k2.put("submittedAt", "2026-09-14T11:15:00");
        k2.put("auditedBy", null);
        k2.put("remarks", "New applicant awaiting RC & PUC verification.");
        kycQueue.add(k2);

        Map<String, Object> k3 = new HashMap<>();
        k3.put("id", 3L);
        k3.put("driverName", "Suresh Kumar");
        k3.put("phone", "+91 98401 33445");
        k3.put("email", "suresh.kumar@cabs.com");
        k3.put("vehiclePlate", "TN 03 EF 9012");
        k3.put("licenseNumber", "DL-TN-03-2020-7712");
        k3.put("licenseExpiry", "2030-11-05");
        k3.put("rcNumber", "RC-TN03EF9012");
        k3.put("insurancePolicy", "POL-BAJAJ-556123");
        k3.put("backgroundCheckStatus", "PENDING_AUDIT");
        k3.put("backgroundCheckDoc", "CERT-BG-CH-8833.pdf");
        k3.put("status", "PENDING_AUDIT");
        k3.put("submittedAt", "2026-09-15T09:00:00");
        k3.put("auditedBy", null);
        k3.put("remarks", "Driver commercial badge renewal uploaded.");
        kycQueue.add(k3);

        return ResponseEntity.ok(kycQueue);
    }

    @PutMapping("/drivers/{id}/kyc-status")
    public ResponseEntity<?> updateDriverKycStatus(
            @PathVariable Long id, 
            @RequestParam String status,
            @RequestParam(required = false, defaultValue = "Approved by Super Admin KYC desk") String remarks) {
        
        Optional<Driver> op = driverRepository.findById(id);
        if (op.isPresent()) {
            Driver d = op.get();
            if ("APPROVED".equalsIgnoreCase(status) || "VERIFIED".equalsIgnoreCase(status)) {
                d.setStatus("ACTIVE");
            } else if ("REJECTED".equalsIgnoreCase(status)) {
                d.setStatus("SUSPENDED");
            }
            driverRepository.save(d);
        }

        Map<String, Object> resp = new HashMap<>();
        resp.put("driverId", id);
        resp.put("kycStatus", status.toUpperCase());
        resp.put("remarks", remarks);
        resp.put("updatedAt", java.time.LocalDateTime.now().toString());
        resp.put("message", "Driver KYC status updated to " + status.toUpperCase());
        return ResponseEntity.ok(resp);
    }

    // ==========================================
    // METROPOLITAN TRANSIT HEATMAP & FLEET GPS
    // ==========================================
    @GetMapping("/analytics/transit-heatmap")
    public ResponseEntity<?> getTransitHeatmap() {
        Map<String, Object> heatmapData = new HashMap<>();

        // Density Clusters
        List<Map<String, Object>> clusters = new ArrayList<>();

        Map<String, Object> c1 = new HashMap<>();
        c1.put("id", "CL-01");
        c1.put("name", "OMR IT Corridor & Sholinganallur");
        c1.put("densityLevel", "CRITICAL_HIGH");
        c1.put("densityColor", "#ef4444");
        c1.put("commutersCount", 498);
        c1.put("activeCabs", 34);
        c1.put("seatDeficit", -64);
        c1.put("lat", 12.9010);
        c1.put("lng", 80.2279);
        clusters.add(c1);

        Map<String, Object> c2 = new HashMap<>();
        c2.put("id", "CL-02");
        c2.put("name", "Kattur ➔ Nungambakkam Institutional Belt");
        c2.put("densityLevel", "HIGH");
        c2.put("densityColor", "#f59e0b");
        c2.put("commutersCount", 380);
        c2.put("activeCabs", 28);
        c2.put("seatDeficit", -12);
        c2.put("lat", 13.0610);
        c2.put("lng", 80.2420);
        clusters.add(c2);

        Map<String, Object> c3 = new HashMap<>();
        c3.put("id", "CL-03");
        c3.put("name", "Tambaram Sanatorium ➔ Guindy Corridor");
        c3.put("densityLevel", "BALANCED");
        c3.put("densityColor", "#10b981");
        c3.put("commutersCount", 240);
        c3.put("activeCabs", 20);
        c3.put("seatDeficit", 18);
        c3.put("lat", 12.9620);
        c3.put("lng", 80.1450);
        clusters.add(c3);

        Map<String, Object> c4 = new HashMap<>();
        c4.put("id", "CL-04");
        c4.put("name", "Anna Nagar West ➔ Kilpauk School Zone");
        c4.put("densityLevel", "HIGH");
        c4.put("densityColor", "#f59e0b");
        c4.put("commutersCount", 310);
        c4.put("activeCabs", 24);
        c4.put("seatDeficit", -8);
        c4.put("lat", 13.0878);
        c4.put("lng", 80.2155);
        clusters.add(c4);

        heatmapData.put("corridorClusters", clusters);

        // Live GPS Fleet Markers
        List<Map<String, Object>> fleetMarkers = new ArrayList<>();

        Map<String, Object> f1 = new HashMap<>();
        f1.put("cabId", "CAB-101");
        f1.put("plate", "TN 01 AB 1234");
        f1.put("driverName", "Kumar Swamy");
        f1.put("driverPhone", "+91 98401 23456");
        f1.put("speedKmh", 36);
        f1.put("route", "Route 1: Kasturba Nagar ➔ Green Valley");
        f1.put("occupancy", "12/14 Seats (85%)");
        f1.put("status", "ON_ROUTE");
        f1.put("lat", 12.9815);
        f1.put("lng", 80.2450);
        fleetMarkers.add(f1);

        Map<String, Object> f2 = new HashMap<>();
        f2.put("cabId", "CAB-102");
        f2.put("plate", "TN 02 CD 5678");
        f2.put("driverName", "Ravi Chandran");
        f2.put("driverPhone", "+91 98401 23457");
        f2.put("speedKmh", 32);
        f2.put("route", "Route 2: Tambaram ➔ Loyola College");
        f2.put("occupancy", "7/7 Seats (100%)");
        f2.put("status", "ON_ROUTE");
        f2.put("lat", 13.0615);
        f2.put("lng", 80.2330);
        fleetMarkers.add(f2);

        Map<String, Object> f3 = new HashMap<>();
        f3.put("cabId", "CAB-103");
        f3.put("plate", "TN 03 EF 9012");
        f3.put("driverName", "Suresh Kumar");
        f3.put("driverPhone", "+91 98401 33445");
        f3.put("speedKmh", 0);
        f3.put("route", "Route 3: Velachery ➔ TCS Siruseri");
        f3.put("occupancy", "0/20 Seats (IDLE)");
        f3.put("status", "STATIONARY");
        f3.put("lat", 12.8390);
        f3.put("lng", 80.2180);
        fleetMarkers.add(f3);

        heatmapData.put("fleetMarkers", fleetMarkers);
        heatmapData.put("activeFleetCount", 86);
        heatmapData.put("totalCommutersMonitored", 1248);
        return ResponseEntity.ok(heatmapData);
    }

    @Autowired
    private SingleTripRepository singleTripRepository;

    @GetMapping("/trips/single")
    public List<SingleTrip> getAllSingleTrips() {
        return singleTripRepository.findAll();
    }
}
