server:
  port: ${PORT:8082}

spring:
  application:
    name: backend-super-admin

  datasource:
    url: jdbc:mysql://${DB_HOST:gateway01.ap-southeast-1.prod.aws.tidbcloud.com}:${DB_PORT:4000}/${DB_NAME:cab_management_db}?createDatabaseIfNotExist=true&useSSL=true&requireSSL=true&serverTimezone=UTC
    username: ${DB_USER:23WUPEUn2RaJBza.root}
    password: ${DB_PASSWORD:MX3QHQY0pJwpmF6p}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: ${REDIS_HOST:magical-shark-297507.upstash.io}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:gQAAAAAABIojAAIgcDE0NTljNmMxYjQwOWY0Yjg3YjdmZTMxY2MzNWJjZmUxNA}
      ssl:
        enabled: ${REDIS_SSL:true}

  sql:
    init:
      mode: always

app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250655368566D5970}
    expiration-ms: ${JWT_EXPIRATION_MS:604800000}

sms:
  provider: ${SMS_PROVIDER:mock}
  apiKey: ${SMS_API_KEY:mock_sms_key}

