server:
  port: ${PORT:8086}

spring:
  application:
    name: backend-student-work

  datasource:
    url: jdbc:mysql://${DB_HOST:gateway01.ap-southeast-1.prod.aws.tidbcloud.com}:${DB_PORT:4000}/${DB_NAME:cab_management_db}?createDatabaseIfNotExist=true&useSSL=true&requireSSL=true&serverTimezone=UTC
    username: ${DB_USER:23WUPEUn2RaJBza.root}
    password: ${DB_PASSWORD:MX3QHQY0pJwpmF6p}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250655368566D5970}
    expiration-ms: ${JWT_EXPIRATION_MS:604800000}

